CREATE TABLE DISEASE (
	DISID INT AUTO_INCREMENT PRIMARY KEY,
	DISNAME VARCHAR(50) NOT NULL,
	DIS_SEV VARCHAR(500) NOT NULL
)


insert into DISEASE VALUES (0 , "X",'X');
insert into DISEASE VALUES (0 , "LUNG DISEASE" , "DANGEROUS");
insert into DISEASE VALUES (0 , "CARDIAC DISEASES", "DANGEROUS");
insert into DISEASE VALUES (0 , "KIDNEY DISEASE" , "DANGEROUS");
insert into DISEASE VALUES (0 , "NEPHROLOGIST DISEASE" , "DISEAASES");
insert into DISEASE VALUES (0 , "NEURAL DISEASE" , "DANGEROUS");
insert into DISEASE VALUES (0 , " ORTHOPEDIC DISEASE" , "DANGEROUS");

insert into DISEASE VALUES (0 , "GENERAL" , "DANGEROUS");
insert into DISEASE VALUES (0 , "GENERAL" , "MEDIUM");
insert into DISEASE VALUES (0 , "GENERAL" , "CASUALITY");
