CREATE table GIVENMEDICINE(
	PID INT ,
	MEDID INT,
	QUANTITY INT,
	SCHEDULETIME VARCHAR(50),
	FOREIGN KEY(PID) REFERENCES PATIENTS(PID) ON DELETE CASCADE,
	FOREIGN KEY(MEDID) REFERENCES MEDICINE(MEDID) ON DELETE CASCADE 

)