CREATE TABLE MEDICINE(
MEDID INT AUTO_INCREMENT PRIMARY KEY, 
MEDNAME VARCHAR(500) NOT NULL, MEDCODE INT NOT NULL, 
DISID INT NOT NULL,
PRICE FLOAT NULL NULL,
FOREIGN KEY (DISID) REFERENCES DISEASE (DISID)  
)
